fixed detecting device language
amplitude/Amplitude-Android pull request #319
Opened 2022-02-13 15:26 UTC by AlexKorRnd

In case of changing the app language programmatically it also needs to call `Locale.setDefault()` because `Locale.getDefault()` is  used in many android SDK places. So it's better to use `Resources.getSystem().getConfiguration().getLocales() ` to detect the device language.

2022-02-25 20:05 UTC, justin-fiedler commented
Hi @AlexKorRnd thank you for the PR. Changes look good but when running test locally I get an error in `DeviceInfo.testGetCountry`. Are you able to run the tests locally and address the issue?

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/5790872/155788512-a6eaa816-a73e-4c78-90ef-8ea0d0c96787.png">

2022-03-01 00:17 UTC, justin-fiedler requested changes
Please fix broken test.

2022-03-14 09:17 UTC, AlexKorRnd commented
@justin-fiedler take a look the new commit [645c76d](https://github.com/amplitude/Amplitude-Android/pull/319/commits/645c76da911f7a18ab449136fa595a438f04fc79)

2022-03-25 04:34 UTC, yuhao900914 approved these changes

2022-03-27 21:08 UTC, merged